os: linux
arch: amd64
dist: bionic
language: go
go:
  - 1.14.x
node_js: "12.16.3"
git:
  depth: 1
install:
  - go get github.com/rakyll/statik
before_script:
  - statik -src=models -f
script:
  - true
after_success:
  - true
before_deploy:
  - sudo apt-get update
  - sudo apt-get -y --no-install-suggests --no-install-recommends install gcc-arm-linux-gnueabi libc6-dev-armel-cross
  - sudo apt-get -y --no-install-suggests --no-install-recommends install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
  - sudo apt-get -y --no-install-suggests --no-install-recommends install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
  - chmod +x ./build.sh
  - ./build.sh -d -r b
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: release/*
  draft: true
  skip_cleanup: true
  on:
    tags: true